import type { NextPage } from "next";
import Head from "next/head";

const Configuration: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="text-white">Saleor App Template - Configuration</div>
      </main>
    </div>
  );
};

export default Configuration;
